object Libs {

    const val coreKtx = "androidx.core:core-ktx:${Versions.core}"
    const val kotlinBom = "org.jetbrains.kotlin:kotlin-bom:${Versions.kotlinBom}"
    const val lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"
    const val activityCompose = "androidx.activity:activity-compose:${Versions.activityCompose}"
    const val composeBom = "androidx.compose:compose-bom:${Versions.composeBom}"
    const val composeUi = "androidx.compose.ui:ui"
    const val composeUiTooling = "androidx.compose.ui:ui-tooling"
    const val uiTestManifest = "androidx.compose.ui:ui-test-manifest"
    const val uiTestJunit = "androidx.compose.ui:ui-test-junit4"
    const val uiGraphics = "androidx.compose.ui:ui-graphics"
    const val uiToolingPreview = "androidx.compose.ui:ui-tooling-preview"
    const val material13 = "androidx.compose.material3:material3"
    const val junit = "junit:junit:${Versions.junit}"
    const val extJunit = "androidx.test.ext:junit:${Versions.junitExt}"
    const val espresso = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    const val systemUiController = "com.google.accompanist:accompanist-systemuicontroller:${Versions.systemUiController}"
    const val sweetToast = "com.github.TalhaFaki:ComposableSweetToast:${Versions.sweetToast}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hiltAndroid}"
    const val hiltNavigation = "androidx.hilt:hilt-navigation:${Versions.hiltNavigation}"
    const val hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:${Versions.hiltNavigationCompose}"
    const val hiltAndroidCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hiltAndroidCompiler}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.roomRuntime}"
    const val roomCompilerAnnotationProcessor  = "androidx.room:room-compiler:${Versions.roomCompilerAnnotationProcessor}"
    const val roomCompilerKsp = "androidx.room:room-compiler:${Versions.roomCompilerKsp}"
    const val roomPaging3 = "androidx.room:room-paging:${Versions.roomPaging3}"
    const val retrofit2 = "com.squareup.retrofit2:retrofit:${Versions.retrofit2}"
    const val okHttp = "com.squareup.okhttp3:okhttp:${Versions.okHttp}"
    const val gson = "com.squareup.retrofit2:converter-gson:${Versions.gson}"
    const val loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.loggingInterceptor}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val navigation = "io.github.raamcosta.compose-destinations:core:${Versions.navigation}"
    const val navigationKsp = "io.github.raamcosta.compose-destinations:ksp:${Versions.navigationKsp}"
    const val coil = "io.coil-kt:coil-compose:${Versions.coil}"
    const val countryCodePicker = "com.github.togisoft:jetpack_compose_country_code_picker:${Versions.countryCodePicker}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout-compose:${Versions.constraintLayout}"

}