object Versions {

    const val core = "1.10.1"
    const val kotlinBom = "1.8.0"
    const val activityCompose = "1.7.2"
    const val lifecycle = "2.6.1"
    const val composeBom = "2023.05.01"
    const val junit = "4.13.2"
    const val junitExt = "1.1.5"
    const val espresso = "3.5.1"
    const val systemUiController = "0.31.3-beta"
    const val sweetToast = "1.0.1"
    const val kotlinCompilerExtensionVersion = "1.4.7"
    const val versionCode = 1
    const val versionName = "1.0"
    const val hiltAndroid = "2.46.1"
    const val hiltNavigation = "1.1.0-alpha02"
    const val hiltNavigationCompose = "1.1.0-alpha01"
    const val hiltAndroidCompiler = "2.46.1"
    const val roomRuntime = "2.5.1"
    const val roomCompilerAnnotationProcessor = "2.5.1"
    const val roomCompilerKsp = "2.5.1"
    const val roomPaging3 = "2.5.1"
    const val retrofit2 = "2.9.0"
    const val okHttp = "5.0.0-alpha.2"
    const val gson = "2.9.0"
    const val loggingInterceptor = "4.5.0"
    const val timber = "5.0.1"
    const val navigation = "1.9.42-beta"
    const val navigationKsp = "1.9.42-beta"
    const val coil = "2.4.0"
    const val countryCodePicker = "1.1.4"
    const val constraintLayout = "1.1.0-alpha10"
}